# Generated by Django 2.1.7 on 2019-02-27 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.AddField(
            model_name='posts',
            name='yayinlayan',
            field=models.ForeignKey(default=1, on_delete=True, related_name='yayinlayan', to=settings.AUTH_USER_MODEL),
        ),
    ]
