# Generated by Django 2.1.7 on 2019-02-27 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kullaniciProfili',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsoyad', models.CharField(blank=True, max_length=30, verbose_name='İsminiz')),
                ('profil', models.OneToOneField(null=True, on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
